[dependencies]
"github.com/dioderobot/demo/components/Diodes_Inc/AP3441LSHEM7B" = "0.1.0"
"github.com/dioderobot/demo/components/Diodes_Inc/AP3441SHEM7B" = "0.1.0"
"github.com/dioderobot/demo/reference/XAL50xx" = "0.1.0"

[assets]
"gitlab.com/kicad/libraries/kicad-symbols/power.kicad_sym" = "9.0.3"
