[dependencies]
"github.com/diodeinc/stdlib" = "0.4.3"
"github.com/dioderobot/demo/components/CSTNE8M00GH5C000R0" = "0.1.0"
"github.com/dioderobot/demo/components/STM32G431C8T6" = "0.1.0"

[assets]
"gitlab.com/kicad/libraries/kicad-symbols/power.kicad_sym" = "9.0.3"
