[workspace]
repository = "github.com/dioderobot/demo"
pcb-version = "0.3"
members = [
    "components/**",
    "reference/*",
    "modules/*",
    "boards/*",
]
vendor = ["github.com/diodeinc/registry/**"]

[access]
allow = ["*"]
