[board]
name = "Renfield"
description = "USB-C PD sink dev board for STM32G0B1 UCPD firmware development."

[dependencies]
"github.com/diodeinc/registry/components/B3U-1000P" = "0.2.1"
"github.com/diodeinc/registry/components/DS04-254-1-04BK-SMT" = "0.3.7"
"github.com/diodeinc/registry/components/Inolux/IN-PI15TAT5R5G5B" = "0.1.1"
"github.com/diodeinc/registry/components/STMicroelectronics/STM32G0B1KxUxN" = "0.1.4"
"github.com/diodeinc/registry/components/STMicroelectronics/TCPP01-M12" = "0.1.1"
"github.com/diodeinc/registry/components/TPD4E05U06QDQARQ1" = "0.4.5"
"github.com/diodeinc/registry/components/Texas_Instruments/CSD1731xQ2" = "0.1.0"
"github.com/diodeinc/registry/components/Texas_Instruments/CSDxxxxxF3" = "0.2.0"
"github.com/diodeinc/registry/components/Texas_Instruments/TPS259482" = "0.1.3"
"github.com/diodeinc/registry/components/Texas_Instruments/TPS74x01P" = "0.1.1"
"github.com/diodeinc/registry/components/Texas_Instruments/TPSM336xx-Q1" = "0.1.0"
"github.com/diodeinc/registry/components/Wago/2060-4xx_998-404" = "0.1.0"
"github.com/diodeinc/registry/connectors/TagConnect" = "0.1.4"
"github.com/diodeinc/registry/connectors/UsbC16P" = "0.1.1"
