[dependencies]
"github.com/diodeinc/stdlib" = "0.4.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M102MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M122MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M222MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M331MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M332MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M472MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M601MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5030M801MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M103MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M153MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M223MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M562MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M682MEC" = "0.1.0"
"github.com/dioderobot/demo/components/Coilcraft/XAL5050M822MEC" = "0.1.0"
