[dependencies]
"github.com/dioderobot/demo/components/Coilcraft/LPS4018-333MRC" = "0.1.0"
"github.com/dioderobot/demo/components/STMicroelectronics/L7986TR" = "0.1.0"
"github.com/dioderobot/demo/components/STMicroelectronics/STPS1L40M" = "0.1.0"
