[board]
name = "DM0003"
description = "Raspberry Pi CM5 carrier board. Features HDMI, PCIe M.2, USB-C PD, and Gigabit Ethernet."

[dependencies]
"github.com/dioderobot/demo/components/ASEK/ASEKM32_768KHZMLMRMT" = "0.1.0"
"github.com/dioderobot/demo/components/G_Switch/MKM11C04MG013" = "0.1.0"
"github.com/dioderobot/demo/components/Hirose/FH12M22SM0_5SH" = "0.1.0"
"github.com/dioderobot/demo/components/JST_JAPAN_SOLDERLESS_TERMINALS/BM04BMSRSSMTB_LF_SN" = "0.1.0"
"github.com/dioderobot/demo/components/JST_JAPAN_SOLDERLESS_TERMINALS/BM10BMSURSMTF_LF_SN" = "0.1.0"
"github.com/dioderobot/demo/components/JST_JAPAN_SOLDERLESS_TERMINALS/SM02BMSRSSMTB_LF_SN" = "0.1.0"
"github.com/dioderobot/demo/components/Nexperia/PUSB3F96X" = "0.1.0"
"github.com/dioderobot/demo/components/OMRON_Electronics/B3UM1000P" = "0.1.0"
"github.com/dioderobot/demo/components/SHOUHAN/TYPE-C24PQT" = "0.1.0"
"github.com/dioderobot/demo/components/Same_Sky/CRJ009-ML4-TH" = "0.1.0"
"github.com/dioderobot/demo/components/Semtech_Corporation/RCLAMP0502BATCT" = "0.1.0"
"github.com/dioderobot/demo/components/TE_Connectivity/1M2199119M3" = "0.1.0"
"github.com/dioderobot/demo/components/Texas_Instruments/HD3SS3212IRKSR" = "0.1.0"
"github.com/dioderobot/demo/components/Texas_Instruments/SN74LVC1G14DRLRG4" = "0.1.0"
"github.com/dioderobot/demo/components/Texas_Instruments/TPD4EUSB30DQAR" = "0.1.0"
"github.com/dioderobot/demo/components/Texas_Instruments/TUSB321RWBR" = "0.1.0"
"github.com/dioderobot/demo/components/XUNPU/HDMI-101S" = "0.1.0"
"github.com/dioderobot/demo/reference/AP22653W6M7" = "0.1.0"
"github.com/dioderobot/demo/reference/AP3441x" = "0.1.0"
"github.com/dioderobot/demo/reference/LIS3DH" = "0.1.0"
"github.com/dioderobot/demo/reference/RP_CM5_IO" = "0.1.0"
"github.com/dioderobot/demo/reference/STMPS2151STR" = "0.1.0"
"gitlab.com/kicad/libraries/kicad-footprints" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols" = "9.0.3"
