[assets]
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-16_3x3mm_P0.5mm_LayoutBorder3x5y.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Motion.kicad_sym" = "9.0.3"
