[board]
name = "DM0002"
description = "Diode Probe (RP2040 CMSIS-DAP)"

[dependencies]
"github.com/diodeinc/stdlib" = "0.4.4"
"github.com/dioderobot/demo/boards/DM0002" = "0.1.7"
"github.com/dioderobot/demo/components/logo/eda" = "0.1.0"
"github.com/dioderobot/demo/modules" = "0.1.0"
