name: PCB Releases

on:
  workflow_dispatch:
  push:

jobs:
  releases:
    permissions:
      contents: read
      id-token: write
    uses: diodeinc/pcb-action/.github/workflows/pcb-release.yml@v2

